Guard with soong namespace
error: vendor/nxp/opensource/sn100x/hidlimpl/1.2/default/Android.bp:1:1: "vendor.nxp.hardware.nfc@1.2-service" depends on undefined module "nfc_nci.nqx.default.hw"
Module "vendor.nxp.hardware.nfc@1.2-service" is defined in namespace "vendor/nxp/opensource/sn100x/hidlimpl" which can read these 2 namespaces: ["vendor/nxp/opensource/sn100x/hidlimpl" "."]
Module "nfc_nci.nqx.default.hw" can be found in these namespaces: ["vendor/nxp/opensource/pn5xx/halimpl" "vendor/nxp/opensource/sn100x/halimpl"]
error: vendor/nxp/opensource/pn5xx/hidlimpl/1.2/default/Android.bp:1:1: "vendor.nxp.hardware.nfc@1.2-service" depends on undefined module "nfc_nci.nqx.default.hw"
Module "vendor.nxp.hardware.nfc@1.2-service" is defined in namespace "vendor/nxp/opensource/pn5xx/hidlimpl" which can read these 2 namespaces: ["vendor/nxp/opensource/pn5xx/hidlimpl" "."]
Module "nfc_nci.nqx.default.hw" can be found in these namespaces: ["vendor/nxp/opensource/pn5xx/halimpl" "vendor/nxp/opensource/sn100x/halimpl"]
error: vendor/nxp/opensource/sn100x/hidlimpl/2.0/default/Android.bp:1:1: "vendor.nxp.hardware.nfc@2.0-service" depends on undefined module "nfc_nci.nqx.default.hw"
Module "vendor.nxp.hardware.nfc@2.0-service" is defined in namespace "vendor/nxp/opensource/sn100x/hidlimpl" which can read these 2 namespaces: ["vendor/nxp/opensource/sn100x/hidlimpl" "."]
Module "nfc_nci.nqx.default.hw" can be found in these namespaces: ["vendor/nxp/opensource/pn5xx/halimpl" "vendor/nxp/opensource/sn100x/halimpl"]
error: vendor/nxp/opensource/sn100x/hidlimpl/2.0/default/Android.bp:1:1: "vendor.nxp.hardware.nfc@2.0-service" depends on undefined module "se_nq_extn_client"
Module "vendor.nxp.hardware.nfc@2.0-service" is defined in namespace "vendor/nxp/opensource/sn100x/hidlimpl" which can read these 2 namespaces: ["vendor/nxp/opensource/sn100x/hidlimpl" "."]
Module "se_nq_extn_client" can be found in these namespaces: ["vendor/nxp/opensource/pn5xx/halimpl" "vendor/nxp/opensource/sn100x/halimpl"]
error: vendor/nxp/opensource/pn5xx/hidlimpl/2.0/default/Android.bp:1:1: "vendor.nxp.hardware.nfc@2.0-service" depends on undefined module "nfc_nci.nqx.default.hw"
Module "vendor.nxp.hardware.nfc@2.0-service" is defined in namespace "vendor/nxp/opensource/pn5xx/hidlimpl" which can read these 2 namespaces: ["vendor/nxp/opensource/pn5xx/hidlimpl" "."]
Module "nfc_nci.nqx.default.hw" can be found in these namespaces: ["vendor/nxp/opensource/pn5xx/halimpl" "vendor/nxp/opensource/sn100x/halimpl"]

Change-Id: I73769567307a3b39c5d584e7dc7305f294c725c3